[workspace]
members = [
    "programs/qpl-staking",
    "programs/qpl-fee-router",
    "programs/qpl-registry",
]

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/solana/**/*.ts"

[programs.localnet]
qpl_staking = "4Q2Np8kL6DWL8tPkApRCfGYvGaPsBSD11BC3rioBSWFn"
qpl_fee_router = "71U4cD7FpKz9epyFNMd4hZLUnY2Qe7WfQzQdrZgmyHrW"
qpl_registry = "CR72aZV3DdD6U7gPo9FYKf22C1tyz9RPufSWddyMeDH7"

[programs.devnet]
qpl_staking = "4Q2Np8kL6DWL8tPkApRCfGYvGaPsBSD11BC3rioBSWFn"
qpl_fee_router = "71U4cD7FpKz9epyFNMd4hZLUnY2Qe7WfQzQdrZgmyHrW"
qpl_registry = "CR72aZV3DdD6U7gPo9FYKf22C1tyz9RPufSWddyMeDH7"

[programs.testnet]
qpl_staking = "4Q2Np8kL6DWL8tPkApRCfGYvGaPsBSD11BC3rioBSWFn"
qpl_fee_router = "71U4cD7FpKz9epyFNMd4hZLUnY2Qe7WfQzQdrZgmyHrW"
qpl_registry = "CR72aZV3DdD6U7gPo9FYKf22C1tyz9RPufSWddyMeDH7"
