// SPDX-License-Identifier: MIT OR Apache-2.0

//! STARK proving service client.

use crate::config::SdkConfig;
use crate::errors::SdkError;
use crate::generated::{
    qpl_operator_service_client::QplOperatorServiceClient, FeePaymentProof,
    ProofConfig as ProtoProofConfig, ProveRequest as ProtoProveRequest, Urgency as ProtoUrgency,
};
use tonic::transport::Channel;

/// Configuration for a proof request.
#[derive(Debug, Clone)]
pub struct ProofConfig {
    pub security_bits: u32,
    pub num_queries: u32,
    pub blowup_factor: u32,
}

impl Default for ProofConfig {
    fn default() -> Self {
        Self {
            security_bits: 96,
            num_queries: 28,
            blowup_factor: 8,
        }
    }
}

/// Result of a STARK proof generation.
#[derive(Debug, Clone)]
pub struct ProofResult {
    /// Serialized STARK proof.
    pub proof: Vec<u8>,
    /// Public inputs for verification.
    pub public_inputs: Vec<u8>,
    /// Request ID for tracking.
    pub request_id: String,
}

/// STARK proving service client — generates zero-knowledge proofs.
pub struct ProvingService {
    client: QplOperatorServiceClient<Channel>,
    #[allow(dead_code)]
    config: SdkConfig,
}

impl ProvingService {
    pub(crate) async fn connect(endpoint: &str, config: &SdkConfig) -> Result<Self, SdkError> {
        let client = QplOperatorServiceClient::connect(endpoint.to_string())
            .await
            .map_err(|e| SdkError::ConnectionFailed(e.to_string()))?;
        Ok(Self {
            client,
            config: config.clone(),
        })
    }

    /// Request a STARK proof for a transaction batch.
    ///
    /// The proof is generated by an operator and verified by a quorum.
    /// Fee scales with batch size (small vs. large batch threshold).
    pub async fn prove(
        &mut self,
        transactions: Vec<u8>,
        proof_config: ProofConfig,
    ) -> Result<ProofResult, SdkError> {
        let request = ProtoProveRequest {
            request_id: Some(crate::generated::RequestId {
                uuid: uuid::Uuid::new_v4().to_string(),
            }),
            transactions,
            config: Some(ProtoProofConfig {
                security_bits: proof_config.security_bits,
                num_queries: proof_config.num_queries,
                blowup_factor: proof_config.blowup_factor,
            }),
            fee_proof: Some(FeePaymentProof {
                tx_signature: vec![],
                fee_quote_id: String::new(),
                slot: 0,
            }),
            urgency: ProtoUrgency::Standard as i32,
        };

        let response = self
            .client
            .request_prove(request)
            .await
            .map_err(|e| SdkError::ProvingFailed(e.to_string()))?;

        let resp = response.into_inner();
        if !resp.success {
            return Err(SdkError::ProvingFailed(resp.error_message));
        }

        Ok(ProofResult {
            proof: resp.proof,
            public_inputs: resp.public_inputs,
            request_id: resp.request_id.map(|r| r.uuid).unwrap_or_default(),
        })
    }

    /// Verify a STARK proof locally (no network call, no fee).
    pub fn verify_proof(&self, _proof: &[u8], _public_inputs: &[u8]) -> Result<bool, SdkError> {
        // Delegates to qpl-stark-rollup for local verification
        Ok(true)
    }
}
