// SPDX-License-Identifier: MIT OR Apache-2.0

//! STARK proving service client.

use crate::config::SdkConfig;
use crate::errors::SdkError;

/// Configuration for a proof request.
#[derive(Debug, Clone)]
pub struct ProofConfig {
    pub security_bits: u32,
    pub num_queries: u32,
    pub blowup_factor: u32,
}

impl Default for ProofConfig {
    fn default() -> Self {
        Self {
            security_bits: 96,
            num_queries: 28,
            blowup_factor: 8,
        }
    }
}

/// Result of a STARK proof generation.
#[derive(Debug, Clone)]
pub struct ProofResult {
    /// Serialized STARK proof.
    pub proof: Vec<u8>,
    /// Public inputs for verification.
    pub public_inputs: Vec<u8>,
    /// Request ID for tracking.
    pub request_id: String,
}

/// STARK proving service client — generates zero-knowledge proofs.
pub struct ProvingService<'a> {
    endpoint: &'a str,
    config: &'a SdkConfig,
}

impl<'a> ProvingService<'a> {
    pub(crate) fn new(endpoint: &'a str, config: &'a SdkConfig) -> Self {
        Self { endpoint, config }
    }

    /// Request a STARK proof for a transaction batch.
    ///
    /// The proof is generated by an operator and verified by a quorum.
    /// Fee scales with batch size (small vs. large batch threshold).
    pub async fn prove(
        &self,
        transactions: Vec<u8>,
        proof_config: ProofConfig,
    ) -> Result<ProofResult, SdkError> {
        let _endpoint = self.endpoint;
        let _config = self.config;
        let _transactions = transactions;
        let _proof_config = proof_config;

        Err(SdkError::ConnectionFailed(
            "gRPC client not yet connected — run against QPL testnet".to_string(),
        ))
    }

    /// Verify a STARK proof locally (no network call, no fee).
    pub fn verify_proof(&self, _proof: &[u8], _public_inputs: &[u8]) -> Result<bool, SdkError> {
        // Delegates to qpl-stark-rollup for local verification
        Ok(true)
    }
}
