fn main() -> Result<(), Box<dyn std::error::Error>> {
    let proto_dir = "../../proto";
    let out_dir = "src/generated";

    // Ensure the output directory exists
    std::fs::create_dir_all(out_dir)?;

    // Only compile protos if protoc is available.
    // The generated code (qpl.v1.rs + mod.rs) is committed to the repo,
    // so builds without protoc will use the pre-generated files.
    // To regenerate: install protoc and rebuild.
    let result = tonic_build::configure()
        .build_server(false)
        .build_client(true)
        .out_dir(out_dir)
        .compile_protos(
            &[
                &format!("{}/qpl_operator.proto", proto_dir),
                &format!("{}/qpl_coordination.proto", proto_dir),
            ],
            &[proto_dir],
        );

    match result {
        Ok(_) => {
            // Regenerated successfully — write mod.rs to include the generated code
            std::fs::write(
                format!("{}/mod.rs", out_dir),
                "// Auto-generated by prost-build. DO NOT EDIT.\n\n#[path = \"qpl.v1.rs\"]\nmod qpl_v1;\n\npub use qpl_v1::*;\n",
            )?;
            println!("cargo:warning=QPL SDK: proto clients generated successfully");
        }
        Err(e) => {
            // protoc not available — use pre-generated files committed to repo
            println!("cargo:warning=QPL SDK: using pre-generated proto clients (protoc not available: {e})");
        }
    }

    Ok(())
}
